# Generated by Django 4.2.7 on 2024-03-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
