# Generated by Django 4.2.7 on 2024-03-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_bid_all_bids_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
