# Generated by Django 4.2.7 on 2024-03-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_all_bids_timestamp_alter_comments_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Title',
            new_name='title',
        ),
    ]
