# Generated by Django 4.2.7 on 2024-03-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_rename_discription_listing_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_bids',
            old_name='listing',
            new_name='for_which_lisitng',
        ),
    ]
