# Generated by Django 4.2.7 on 2024-03-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_all_bids_for_which_lisitng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_bids',
            old_name='for_wh_lisitng',
            new_name='for_which_lisitng',
        ),
    ]
