# Generated by Django 4.2.7 on 2024-03-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_for_which_lisitng_all_bids_for_which_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='initial_bid',
        ),
    ]
