# Generated by Django 4.2.7 on 2024-03-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_listing_initial_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_bids',
            name='for_which_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.listing'),
        ),
    ]
