# Generated by Django 4.2.7 on 2024-04-04 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_all_bids_for_which_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='for_which_listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.listing'),
        ),
    ]
