# Generated by Django 4.2.7 on 2024-04-11 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comments_for_which_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='catagorie',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('for_which_lsiting', models.ManyToManyField(to='auctions.listing')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
