# Generated by Django 4.2.7 on 2024-04-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_rename_catagorie_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_auction_active',
            field=models.BooleanField(null=True),
        ),
    ]
